# Dockerfile.frontend

# 使用轻量级的 Nginx 镜像
FROM nginx:alpine

# 1. 替换 Nginx 的默认配置文件
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# 2. 将你本地的 static 文件夹内容，复制到 Nginx 存放网页的目录里
COPY ./static /usr/share/nginx/html

# 3. 暴露 80 端口
EXPOSE 80

# 启动 Nginx
CMD ["nginx", "-g", "daemon off;"]